name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image
        run: |
          az acr login --name ${{ secrets.AZURE_ACR_NAME }}
          docker build -t ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/fastapi-app:latest .
          docker push ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/fastapi-app:latest

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set --name ${{ secrets.AZURE_APP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --docker-custom-image-name ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/fastapi-app:latest
